var musics = [
{
    "id":"1",
    "name":"起风了",
    "size":"5178838",
    "path":"asserts/买辣椒也用券-起风了.mp3"
},
{
    "id":"2",
    "name":"广东爱情故事",
    "size":"3430487",
    "path":"asserts/广东雨神-广东爱情故事.mp3"   
},
{
    "id":"3",
    "name":"醉赤壁",
    "size":"16987463",
    "path":"asserts/林俊杰-醉赤壁.mp3"   
},
{
    "id":"4",
    "name":"有何不可",
    "size":"4506718",
    "path":"asserts/许嵩-有何不可.mp3"   
}
];
